### ISSUE TITLE
Chequear cache del browser

### ISSUE THREAD

**Issue by elnanner** [elnanner/frontendCarteleras#1]
Fijarse siempre que los browsers cachean, me volviò loco eso en el frontend. 
Si ves que no anda como deberia, borrar la cache @rama64

**Comment by rama64** [comment]
jajaja obvio xD   
Ahí estoy viendo si puedo hacer andar las notas (así para que se vean). Si anda eso, faltaría hacer el crud de pizarra (siguiente a eso) y quedarían solo ver detalles y discutir dónde van a ir las futuras cosas, etc :)   estás laburando?

**Comment by elnanner** [comment]
Yo lo solucioné usando firefox
